# Generated by Django 5.1.2 on 2025-09-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-appointment_date'], 'permissions': [('can_change_appointment_status', 'Can change appointment status'), ('can_view_all_appointments', 'Can view all appointments')]},
        ),
        migrations.AlterModelOptions(
            name='counsellingsession',
            options={'permissions': [('can_write_session_notes', 'Can write session notes'), ('can_view_session_history', 'Can view session history')]},
        ),
        migrations.AlterModelOptions(
            name='counsellor',
            options={'permissions': [('can_view_student_records', 'Can view student records'), ('can_manage_schedule', 'Can manage schedule'), ('can_write_session_notes', 'Can write session notes'), ('can_view_all_appointments', 'Can view all appointments'), ('can_manage_own_availability', 'Can manage own availability')]},
        ),
        migrations.AlterModelOptions(
            name='counsellorreview',
            options={'permissions': [('can_write_review', 'Can write review'), ('can_moderate_reviews', 'Can moderate reviews')]},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_access_admin_panel', 'Can access admin panel'), ('can_manage_users', 'Can manage users'), ('can_manage_appointments', 'Can manage appointments'), ('can_view_reports', 'Can view reports'), ('can_manage_counsellors', 'Can manage counsellors')]},
        ),
        migrations.AlterModelOptions(
            name='sessiondocument',
            options={'permissions': [('can_upload_documents', 'Can upload documents'), ('can_view_documents', 'Can view documents')]},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': [('can_view_own_appointments', 'Can view own appointments'), ('can_book_appointment', 'Can book appointment'), ('can_view_own_records', 'Can view own records'), ('can_cancel_appointment', 'Can cancel appointment')]},
        ),
        migrations.AddField(
            model_name='counselloravailability',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
